a = int(input("Enter first number "))
b = int(input("Enter second number "))
sum = a + b
sub = a - b
mul = a * b
div = a / b
mod = a % b
exp = a ** b
flr = a // b
print(f"sum of {a} and {b} = {sum}")
print(f"substarction of {a} and {b} = {sub}")
print(f"multiplication of {a} and {b} = {mul}")
print(f"div of {a} and {b} = {div}")
print(f"mod of {a} and {b} = {mod}")
print(f"exponention of {a} and {b} = {exp}")
print(f"floor div of {a} and {b} = {flr}")
